version: "3"

services:
  webserver:
    image: nginx:latest
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf  
      - ./Docker/public:/var/www/html/public  
      - ./Docker/app/Views:/var/www/html/Views                       
    depends_on:
      - php
      - db

  php:
    build:
      context: ./services/php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./Docker/app:/var/www/html/app             
      - ./Docker/config:/var/www/html/config        
      - ./Docker/public:/var/www/html/public        
    expose:
      - "9000"
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "cv_db"
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysqldata: {}
