version: "3"

services:
  webserver:
    image: nginx:latest
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./Docker/app/public:/var/www/html/public 
    depends_on:
      - php
    command: /bin/sh -c "echo 'Your website is running on Nginx' && nginx -g 'daemon off;'"

  php:
    build:
      context: ./services/php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./Docker/app/public:/var/www/html/public 
      - ./src:/var/www/html/src
    expose:
      - "9000"

  db:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "cv_db"
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"

volumes:
  mysqldata: {}
