version: "3"

services:
  webserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    depends_on:
      - app
    command: /bin/sh -c " echo 'Your website is running on Nginx' && nginx -g 'daemon off;'"
  app:
    build: 
      context: ./services/php
      dockerfile: dockerfile
    volumes:
      - ./app/:/app
    expose:
      - 9000
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "cv_db"
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
volumes:
  mysqldata: {}
